/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate */
        get: operations["validate_api_auth_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Containers */
        get: operations["list_containers_api_containers_get"];
        put?: never;
        /** Create Container */
        post: operations["create_container_api_containers_post"];
        /** Delete Containers */
        delete: operations["delete_containers_api_containers_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Container */
        get: operations["get_container_api_containers__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Container */
        post: operations["start_container_api_containers__id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Container */
        post: operations["stop_container_api_containers__id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart Container */
        post: operations["restart_container_api_containers__id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename Container */
        post: operations["rename_container_api_containers__id__rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Container Logs */
        get: operations["container_logs_api_containers__id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Container Diff */
        get: operations["container_diff_api_containers__id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Container */
        post: operations["commit_container_api_containers__id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exec Container */
        post: operations["exec_container_api_containers__id__exec_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/containers/{id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Terminal Ticket Endpoint */
        post: operations["create_terminal_ticket_endpoint_api_containers__id__terminal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_api_images_get"];
        put?: never;
        post?: never;
        /** Delete Images */
        delete: operations["delete_images_api_images_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_images__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pull Image */
        post: operations["pull_image_api_images_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tag Image */
        post: operations["tag_image_api_images__id__tag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image History */
        get: operations["image_history_api_images__id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/search/{keyword}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Images */
        get: operations["search_images_api_images_search__keyword__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Networks */
        get: operations["list_networks_api_networks_get"];
        put?: never;
        /** Create Network */
        post: operations["create_network_api_networks_post"];
        /** Delete Networks */
        delete: operations["delete_networks_api_networks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network */
        get: operations["get_network_api_networks__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Network */
        post: operations["connect_network_api_networks__id__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networks/{id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect Network */
        post: operations["disconnect_network_api_networks__id__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Volumes */
        get: operations["list_volumes_api_volumes_get"];
        put?: never;
        /** Create Volume */
        post: operations["create_volume_api_volumes_post"];
        /** Delete Volumes */
        delete: operations["delete_volumes_api_volumes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volumes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volume */
        get: operations["get_volume_api_volumes__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Version */
        get: operations["system_version_api_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommitRequest */
        CommitRequest: {
            /** Name */
            name: string;
            /** Tag */
            tag?: string | null;
            /** Message */
            message?: string | null;
            /** Author */
            author?: string | null;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /** Container Id */
            container_id: string;
            /** Ipv4 Address */
            ipv4_address?: string | null;
        };
        /** ContainerCreate */
        ContainerCreate: {
            /** Image */
            image: string;
            /** Command */
            command: string;
            /** Name */
            name?: string | null;
            /**
             * Interactive
             * @default false
             */
            interactive: boolean;
            /**
             * Tty
             * @default false
             */
            tty: boolean;
            /**
             * Ports
             * @default []
             */
            ports: components["schemas"]["PortMapping"][];
            /**
             * Volumes
             * @default []
             */
            volumes: components["schemas"]["VolumeMapping"][];
        };
        /** ContainerDiff */
        ContainerDiff: {
            /**
             * Add
             * @default []
             */
            add: string[];
            /**
             * Change
             * @default []
             */
            change: string[];
            /**
             * Delete
             * @default []
             */
            delete: string[];
            /**
             * Other
             * @default []
             */
            other: string[];
        };
        /** ContainerItem */
        ContainerItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            image: components["schemas"]["ImageItem"];
            /** Create Time */
            create_time: string;
            /** Status */
            status: string;
            /** Command */
            command?: string | null;
            /** Tty */
            tty?: boolean | null;
            /** Interactive */
            interactive?: boolean | null;
            network?: components["schemas"]["ContainerNetwork"] | null;
            /** Mounts */
            mounts?: components["schemas"]["Mount"][] | null;
        };
        /** ContainerNetwork */
        ContainerNetwork: {
            /** Ip */
            ip?: string | null;
            /** Prefix */
            prefix?: number | null;
            /** Gateway */
            gateway?: string | null;
            /** Mac Address */
            mac_address?: string | null;
            /** Ports */
            ports?: components["schemas"]["PortMapping"][] | null;
        };
        /** DeleteImagesRequest */
        DeleteImagesRequest: {
            /** Ids */
            ids: string[];
            /**
             * Tag Only
             * @default false
             */
            tag_only: boolean;
        };
        /**
         * DeleteResult
         * @description Failed ids mapped to their error message; empty means fully succeeded.
         */
        DeleteResult: {
            /**
             * Failed
             * @default {}
             */
            failed: {
                [key: string]: string;
            };
        };
        /** DisconnectRequest */
        DisconnectRequest: {
            /** Container Id */
            container_id: string;
        };
        /** ExecRequest */
        ExecRequest: {
            /** Command */
            command: string;
            /**
             * Interactive
             * @default true
             */
            interactive: boolean;
            /**
             * Tty
             * @default true
             */
            tty: boolean;
            /**
             * Privileged
             * @default false
             */
            privileged: boolean;
        };
        /** ExecResult */
        ExecResult: {
            /** Exit Code */
            exit_code: number;
            /** Output */
            output: string;
        };
        /** ExposedPort */
        ExposedPort: {
            /** Port */
            port: number;
            /** Protocol */
            protocol: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Id */
            id: string;
            /**
             * Created By
             * @default
             */
            created_by: string;
            /** Created Time */
            created_time: string;
            /**
             * Size
             * @default 0
             */
            size: number;
            /** Tags */
            tags?: string[] | null;
            /** Comment */
            comment?: string | null;
        };
        /** IdsRequest */
        IdsRequest: {
            /** Ids */
            ids: string[];
        };
        /** ImageItem */
        ImageItem: {
            /** Id */
            id: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Author
             * @default
             */
            author: string;
            /** Create Time */
            create_time: string;
            /**
             * Size
             * @default 0
             */
            size: number;
            /** Command */
            command?: string | null;
            /** Tty */
            tty?: boolean | null;
            /** Interactive */
            interactive?: boolean | null;
            /** Architecture */
            architecture?: string | null;
            /** Os */
            os?: string | null;
            /** Ports */
            ports?: components["schemas"]["ExposedPort"][] | null;
        };
        /** ImageSearchItem */
        ImageSearchItem: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Star Count */
            star_count?: number | null;
            /** Is Official */
            is_official?: boolean | null;
            /** Is Automated */
            is_automated?: boolean | null;
        };
        /** Mount */
        Mount: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Driver */
            driver?: string | null;
            /** Mode */
            mode?: string | null;
            /** Src */
            src?: string | null;
            /** Dest */
            dest?: string | null;
        };
        /** NetworkCreate */
        NetworkCreate: {
            /** Name */
            name: string;
            /** Driver */
            driver: string;
            /**
             * Attachable
             * @default true
             */
            attachable: boolean;
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["Option"][];
            /** Subnet */
            subnet?: string | null;
            /** Gateway */
            gateway?: string | null;
            /** Ip Range */
            ip_range?: string | null;
        };
        /** NetworkItem */
        NetworkItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Driver */
            driver?: string | null;
            /** Scope */
            scope?: string | null;
            /** Create Time */
            create_time: string;
            /**
             * Container Num
             * @default 0
             */
            container_num: number;
            /** Subnet */
            subnet?: string | null;
            /** Gateway */
            gateway?: string | null;
            /** Ip Range */
            ip_range?: string | null;
            /** Ipam Driver */
            ipam_driver?: string | null;
            /** Internal */
            internal?: boolean | null;
            /** Attachable */
            attachable?: boolean | null;
            /** Options */
            options?: {
                [key: string]: string;
            } | null;
            /** Containers */
            containers?: components["schemas"]["ContainerItem"][] | null;
        };
        /** Option */
        Option: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** PortMapping */
        PortMapping: {
            /** Port */
            port: number;
            /**
             * Protocol
             * @default tcp
             */
            protocol: string;
            /**
             * Listen Ip
             * @default 0.0.0.0
             */
            listen_ip: string;
            /** Listen Port */
            listen_port: number;
        };
        /** ProjectInfo */
        ProjectInfo: {
            /** Version */
            version: string;
            /** Hostname */
            hostname: string;
            /** Python */
            python: string;
            /** Os */
            os: string;
            /** Arch */
            arch: string;
            /** Kernel */
            kernel: string;
        };
        /** PullCreated */
        PullCreated: {
            /** Pull Id */
            pull_id: string;
        };
        /** PullRequest */
        PullRequest: {
            /** Name */
            name: string;
            /** Tag */
            tag?: string | null;
        };
        /** RenameRequest */
        RenameRequest: {
            /** Name */
            name: string;
        };
        /** SettingsData */
        SettingsData: {
            /**
             * Docker Host
             * @default unix:///var/run/docker.sock
             */
            docker_host: string;
        } & {
            [key: string]: unknown;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Docker Host */
            docker_host?: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** SystemVersion */
        SystemVersion: {
            project: components["schemas"]["ProjectInfo"];
            /** Docker */
            docker: {
                [key: string]: unknown;
            };
        };
        /** TagRequest */
        TagRequest: {
            /** Name */
            name: string;
            /** Tag */
            tag?: string | null;
        };
        /** TagResult */
        TagResult: {
            /** Success */
            success: boolean;
        };
        /** TerminalRequest */
        TerminalRequest: {
            /** Command */
            command?: string | null;
        };
        /** TerminalTicket */
        TerminalTicket: {
            /** Ticket */
            ticket: string;
            /** Expires */
            expires: number;
        };
        /** ValidateResponse */
        ValidateResponse: {
            /**
             * Valid
             * @default true
             */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeCreate */
        VolumeCreate: {
            /** Name */
            name: string;
            /** Driver */
            driver?: string | null;
            /**
             * Driver Opts
             * @default []
             */
            driver_opts: components["schemas"]["Option"][];
        };
        /** VolumeItem */
        VolumeItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Driver */
            driver?: string | null;
            /** Mount Point */
            mount_point?: string | null;
            /** Scope */
            scope?: string | null;
            /** Create Time */
            create_time: string;
            /** Driver Opts */
            driver_opts?: {
                [key: string]: string;
            } | null;
        };
        /** VolumeMapping */
        VolumeMapping: {
            /** Path */
            path: string;
            /** Bind */
            bind: string;
            /**
             * Mode
             * @default rw
             */
            mode: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    validate_api_auth_validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
        };
    };
    list_containers_api_containers_get: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_container_api_containers_post: {
        parameters: {
            query?: {
                run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContainerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_containers_api_containers_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_container_api_containers__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_container_api_containers__id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_container_api_containers__id__stop_post: {
        parameters: {
            query?: {
                timeout?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_container_api_containers__id__restart_post: {
        parameters: {
            query?: {
                timeout?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_container_api_containers__id__rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    container_logs_api_containers__id__logs_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    container_diff_api_containers__id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_container_api_containers__id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exec_container_api_containers__id__exec_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_terminal_ticket_endpoint_api_containers__id__terminal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_images_api_images_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteImagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_images__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_image_api_images_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PullRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tag_image_api_images__id__tag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_history_api_images__id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_images_api_images_search__keyword__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageSearchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_networks_api_networks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkItem"][];
                };
            };
        };
    };
    create_network_api_networks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_networks_api_networks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_network_api_networks__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_network_api_networks__id__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_network_api_networks__id__disconnect_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisconnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_volumes_api_volumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeItem"][];
                };
            };
        };
    };
    create_volume_api_volumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolumeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_volumes_api_volumes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_api_volumes__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_version_api_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemVersion"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsData"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
